### ISSUE TITLE
ExamClass Revision Proposal v.2019.Q1

### ISSUE THREAD

**Issue by whizkid77** [cspa-exam/tsc#6]
# [ExamClass](./docs/schema/ExamClass.md) Revision Proposal v.2019.Q1

## Core Exam

Based on informal TSC polling, the following changes are proposed to the Core exam class:

- Remove **Operating Systems**.  OS will no longer be covered either on Core or Quizzes.
- Remove **Systems design, architecture, and infrastructure**.  This will be moved to a separate Quiz.

The Core Exam remains a graded, proctored exam that is administered on a fixed schedule.

![cspa-subjects-core-assessments-v3](https://user-images.githubusercontent.com/2087689/51347265-73917b80-1a54-11e9-9b31-d4b472f46a27.png)

For details on each topic, please refer to the [topic tree](https://cspa.io/topics).

## Quizzes

Additionally, we introduce 5 *Quizzes*, a set of shorter, subject-based assessments.  These are individual, non-proctored assessments that are given on-demand, generally as part of an employer's interview process.  Because of this, quizzes cannot have human graders, so they are either autograded (i.e. multiple choice and short code answer questions) or not graded at all (i.e. open response questions).  To avoid excessive fragmentation, we limit it to 5 quizzes, and scale up as supply and demand increase.

![cspa-subjects-quizzes](https://user-images.githubusercontent.com/2087689/51293601-83fa1580-19c4-11e9-8511-3c012e478ca7.png)

### Web Developer Generalist

The **Web Developer Generalist** quiz is suitable for junior and mid-level candidates who plan to work in a linux-based web tech stack. It covers the web stack from back-end down to ops and single machine architecture. The multiple choice section is predominantly knowledge- and experience-based, while the final section tests their ability to code in a language they are comfortable with.

High scoring candidates:

- have solid coding fundamentals for algorithms and data structures
- understand high level web architecture, including TCP/IP, HTTP and data storage systems
- have some understanding of modern tools such as version control, remotely logging into machines, navigating shell, and transferring files

### Front-End React JS

The **Front-End React JS** quiz is suitable for junior and mid-level web front-end candidates. High scoring candidates:

- are able to write vanilla HTML, CSS, and JavaScript
- have some experience building React apps
- are familiar with using and building React components
- have strong coding fundamentals for algorithms and data structures

### Algorithms & Data Structures

**Algorithms & Data Structures** tests a candidate's ability to traverse and analyze complex data structures.

Skills tested:

- functional programming
- recursion
- traversing nested arrays
- stateful traversal

Candidates have two hours to complete the two questions, with an optional 30 minute break in between. They can use any one of our supported languages, and are graded on the number of test cases they pass.

### Machine Learning

The **Machine Learning** quiz is intended for mid-to-senior level big data and/or machine learning engineers.

*Details TBD*

### Systems Design, Architecture, and Infrastructure

The **Systems Design, Architecture, and Infrastructure** quiz is intended for senior architects and back end software engineers.

Given a problem specification, high scoring candidates are able to:
- Evaluate possible solutions to determine the best course of action
- Design a system that conforms to the specification on attributes such as reliability, performance, accessibility, maintainability, and extensibility
- Make knowledgeable choices on components of a system

**Comment by whizkid77** [comment]
Still a bit iffy on the Front-End React JS quiz.  It's intended as an experiment for proprietary frameworks, but might consider replacing it with a vanilla front-end quiz to keep it general.

**Comment by booi** [comment]
> Still a bit iffy on the Front-End React JS quiz. It's intended as an experiment for proprietary frameworks, but might consider replacing it with a vanilla front-end quiz to keep it general.

Well technically ReactJS is open source (MIT) so I think it's "probably fine" to leave in. It's importance should be downplayed in favor of vanilla front-end though. As with any framework, it may fall out of favor but the standards won't change.

**Comment by etrepum** [comment]
I’m in favor of having framework-specific questions, few companies are doing vanilla JS these days and there really aren’t that many JS frameworks in popular use today to support. It doesn’t seem feasible to have this kind of test set in stone for years anyway, might as well just plan to have it follow de facto industry framework standards the same way you’d add or remove programming languages over time.

JS standards do change in an additive way, and the de facto subset of those standards changes in subtractive way too. There aren’t a whole lot of reasons to learn XHR over fetch, or getElementsBy APIs over querySelectorAll, for example.

**Comment by davidyang** [comment]
For the removal of Operating Systems, is that just the following topics?  The rest look quite useful and are often hard to test for in algorithmic interviews (the tools, git, networking etc.)

## Operating systems

- File systems (descriptors, inodes, journaling, pipes, sockets) (example)
- Syscalls and interrupts
- Processes, concurrency, threading, and scheduling
- Locks and transactions
- Memory systems (allocations, paging, virtual addressing, garbage collection)
- Storage systems and their tradeoffs (SSD, magnetic, cloud) (example)
- User vs. kernel space

**Comment by whizkid77** [comment]
@davidyang yes, "Operating Systems" are those topics you listed (basically OS internals).  "Tools" (github, text editors, ssh, etc) are broken out into its own box.  "Networking" is also separated (http, tcp/ip, DNS, etc).

**Comment by macrigiuseppe** [comment]
I don't think functional programming should be part of __Algorithm and Data Structures__ section because it's a programming style.

**Comment by etrepum** [comment]
@macrigiuseppe If persistent/immutable data structures are part of the curriculum, it would be hard to cover that without addressing functional programming in some way. Functional programming also has some relation to React in spirit if not in practice.

**Comment by etrepum** [comment]
It also depends on what is actually meant by functional programming in this context. Maybe we’re just talking about methods such as `Array.prototype.{map, filter, reduce, ...}` which are considered by some to be functional programming.

**Comment by whizkid77** [comment]
Re: functional programming -- the details for each category can be worked out in each working group.  @macrigiuseppe has a good point -- and the Topic Tree page will be changed to reflect the split of (Algs & DS) and (Programming Languages) if this proposal is approved.

Re: ReactJS -- I suppose we can have two distinct sections on this quiz: 1) vanilla non-React 2) React-specific.  People who don't care about the React-specific part can just ignore that subscore.

**Comment by dfujiwara** [comment]
FWIW, I have seen some frontend quizzes focus on the async paradigm (promises, async/await), and some people get tripped up with those type of questions. I recommend putting that in the vanilla non-React portion of the quiz.

**Comment by dfujiwara** [comment]
In related question about having framework-specific quiz/questions, I wonder if modern tooling related questions should be bundled up in FrontEnd/React JS quiz. I am not a JS dev, but tooling is something that trips me up if I stay away from any particular technology for some time (testing, dependency manager, bundler, etc)

**Comment by dfujiwara** [comment]
I think more and more companies put emphasize on automated testing. In fact, during my current company's phone screen, if candidates don't think about writing tests it's considered a red flag. What do you think of incorporating testing related questions to the exam and/or quizzes?

**Comment by willmsalas** [comment]
@dfujiwara do you have a way in mind that we could incorporate test-related questions in a way that is not open-ended and can be automatically graded? (I agree with tests being super important but I see the same problem here as with the "Architecture" questions, maybe you have thought of a way to solve this?)

**Comment by booi** [comment]
> @dfujiwara do you have a way in mind that we could incorporate test-related questions in a way that is not open-ended and can be automatically graded? (I agree with tests being super important but I see the same problem here as with the "Architecture" questions, maybe you have thought of a way to solve this?)

Actually I think a hands-on test-related question might be easy to automatically grade.  

Given a blackbox function: 
fun factorial(n: Int): Int

Write a test suite to catch errors etc... Automatically run the test suite?

**Comment by whizkid77** [comment]
Proposal passed 11-0
